version: '3'

services:
  db:
    image: postgres:11.2-alpine
    container_name: sme_ptrf-postgres-local
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345qw
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ptrf
    volumes:
      - ../ptrf-postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5433:5432
  
  pgadmin4:
    image: dpage/pgadmin4
    container_name: sme_ptrf-postgres-pgadmin4-local
    restart: always
    volumes:
      - ./bkp:/var/lib/pgadmin/storage/
    ports:
      - 9091:80
    environment:
      PGADMIN_DEFAULT_EMAIL: anderson.morais@amcom.com.br
      PGADMIN_DEFAULT_PASSWORD: adminadmin
    depends_on:
      - db

  redis:
    image: redis:5.0
    container_name: sme-ptrf-redis-local
    restart: always
    ports:
      - "6380:6379"
  
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sme_ptrf_backend
    container_name: sme_ptrf_backend
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: /start
    links:
      - db:db
  
  celeryworker:
    <<: *django
    image: sme_ptrf_backend_local_celeryworker
    container_name: sme_ptrf_backend_local_celeryworker
    depends_on:
      - redis
      
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: sme_ptrf_backend_local_celerybeat
    container_name: sme_ptrf_backend_local_celerybeat
    depends_on:
      - redis
      
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: sme_ptrf_flower
    container_name: sme_ptrf_flower
    ports:
      - "5555:5555"
    command: /start-flower
  
networks:
  default:
    external:
      name: sme-ptrf-network
